apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-node
    spec:
      containers:
        - name: nfs
          image: blue1st/nfs4:latest
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
            - name: portmapper 
              containerPort: 111
          volumeMounts:
            - name: nfs-dir 
              mountPath: /exports
      volumes:
        - name: nfs-dir 
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs 
  labels:
    app: nfs-node
spec:
  ports:
    - port: 2049 
      protocol: TCP
      name: nfs
    - port: 111 
      protocol: UDP 
      name: portmapper
  clusterIP: # edit this 
  selector:
    app: nfs-node
